### ISSUE TITLE
Network.set() fails if network node IDs are not sequentially ordered integers starting at 0

### ISSUE THREAD

**Issue by mxndrwgrdnr** [UDST/pandana#58] opened 2017-03-07 19:45 UTC
I ran into this problem while running an instance of bayarea_urbansim using my own network where the node ids were OSM node IDs. A lot of digging led me to identify net.set() as the source of my problems. Network.set() relies on [this](https://github.com/UDST/pandana/blob/master/pandana/network.py#L168) class method when relating the node IDs of the network to the node IDs of the variable that is being set. The problem is that this function, `self._node_indexes()`, in turn relies on a merge of the node IDs from the variable in question with the node _indices_ of [this](https://github.com/UDST/pandana/blob/master/pandana/network.py#L119-L120) class object, `self.node_idx`, which for some reason is defined as a NumPy arange(). Thus, if the node IDs of the variable you wish to compute with Network.set() are not themselves sequentially ordered integers a-la a NumPy arange(), the network will not be able to find any matching POI's, which is precisely the problem that I was encountering. I'm sure there is some reason why `self.node_idx` is defined the way it is, but without knowing the rationale I don't know whether it makes more sense to implement a fix or to instead update the documentation to reflect the requirement that network node IDs be sequentially ordered IDs.

**Comment by sablanchard** [comment] 2017-03-07 19:51
Thank you Max. We will look into this but first, @fscottfoti do you have any comments on the initial architecture of this, rational, or best way to move forward?

**Comment by fscottfoti** [comment] 2017-03-07 20:41
Not off the top of my head but I will take a look in depth later today...

**Comment by fscottfoti** [comment] 2017-03-07 22:37
Hmm, this is complicated and I'm not sure I have this all sorted out in my head, but this is what I remember...

Basically in the internal C++ code (in contraction hierarchies) node_ids are actually indexes into an array so yeah internally they have to be contiguous starting at 0, but they shouldn't be externally so the user never has to know about that.

I'm pretty sure net.set deals with that correctly [here](https://github.com/UDST/pandana/blob/master/pandana/network.py#L228) by mapping external ids to internal ids.  That's pretty well tested code so I think there's more to it than that.  Not saying there's no bug, but I mean, it's been used a lot without 0-based indexes so I think it's mostly working.

I'm also a bit confused.  You're doing poi searches right, not aggregations?  If that's the case you don't use `set` at all - you use set_pois??

**Comment by mxndrwgrdnr** [comment] 2017-03-08 02:17
Sorry for the confusion, shouldn't have said POIs. This is an aggregation, specifically the regional_vars calculation which involves regional POIs, thus the confusion. 

It looks like I may have overlooked [this](https://github.com/UDST/pandana/blob/master/pandana/network.py#L120) line where the index of `self.node_idx` is defined as the index of the nodes dataframe. That makes sense now. Let's leave the issue open while I keep digging for the root cause then, because my issue resolved itself as soon as I converted my node IDs to 0-based sequential integers. I'll try to put together a script or a notebook or something that demonstrates the issue.

**Comment by fscottfoti** [comment] 2017-03-08 17:17
Yeah, a simple test would be great - I could take a look

**Comment by mxndrwgrdnr** [comment] 2017-03-08 22:39
OK, I put together an IPython notebook [here](https://drive.google.com/file/d/0B3AJ8un93U6wcFZrczFFSGRlVjA/view?usp=sharing) along with the data files you'll need to run it. Warning, its a a fairly big network, and the aggregations and precompute steps each take about 3-5 minutes to run on my laptop with 16GB of RAM. Check it out when you get a chance and let me know what you think.

**Comment by fscottfoti** [comment] 2017-03-09 22:48
This example is super duper useful - thanks for putting together and especially for sharing the data.  Turns out the bug is that when you write the buildings table to csv and read it back in, tmnode_id becomes a string, whereas when nodes is stored in the hdf5 the tmnode_id stays in int.  This means you can't align the two indexes (strings != ints).  On top of that the notebook appears to hide that from you, whereas although it took me a while to see it, the interpreter shows it clearly.  Anyway, bottom line is it's not a bug in pandana, which I figure it couldn't be since I've never used consecutive node_ids.  The pandas index bug strikes again!

**Comment by mxndrwgrdnr** [comment] 2017-03-09 23:07
Interesting, although slightly unsatisfactory! This explains why the problem occurs when reading the buildings table from .csv, but it doesn't explain how/why the issue was happening during the course of a regular UrbanSim run. I only wrote out the buildings table to .csv for the purpose of debugging. I guess the next would be to write the buildings table out to hdf5 instead, and go from there. I'll report back if I make any progress there, but feel free to close the issue in the meantime. Thanks for taking a look, though. Nice catch!

**Comment by fscottfoti** [comment] 2017-03-09 23:15
I think I got that wrong - osm_nodes.index is a string and osm_buildings.tmnode_id is an int.

I'm also seeing something strange.

```
In [27]: osm_buildings.tmnode_id.isin(osm_nodes.index).value_counts()
Out[27]: 
True    1843351
Name: tmnode_id, dtype: int64
```

This seems to indicate that it does align, even with the different types.

But that's not how pandana does it - it uses a [pd.merge](https://github.com/UDST/pandana/blob/master/pandana/network.py#L170), which clearly isn't working.  So I'm not sure yet that that's the whole story...

**Comment by fscottfoti** [comment] 2017-03-09 23:16
Incidentally, you don't want to see `Removed 1843351 rows because they contain missing values` - that means it didn't align.

**Comment by fscottfoti** [comment] 2017-03-09 23:21
I can confirm that doing this `osm_nodes.index = osm_nodes.index.astype('int')` before the pdna.Network call fixes the alignment issue, so those types are the problem.

I'm at a loss as to why isin returns all true - that seems like a pandas bug?

**Comment by fscottfoti** [comment] 2017-03-09 23:32
Sorry I've got it now.  Pandana casts to int when it initializes.  This keeps the series from aligning.  I think the cast is unnecessary though.  It has to be an int internally but not externally.  We've probably only used ints before.

**Comment by mxndrwgrdnr** [comment] 2017-03-10 18:44
OK I think that makes sense. The working hypothesis is that if I were to recast the node ID column of my non-zero-indexed nodes table, then everything should work? I'll try that in a full urbansim run and report back.

**Comment by fscottfoti** [comment] 2017-03-10 18:51
Yes, turns out @sablanchard already knew that pandana had an issue with using strings as nodeids.  It should be fixable.

**Comment by mxndrwgrdnr** [comment] 2017-03-10 18:55
Oh OK, cool. I'll go ahead and mark this issue closed then?

**Comment by fscottfoti** [comment] 2017-03-10 19:15
I'd leave it open as a reminder to fix Pandana to support strings.  But you should be fine with the current version if you convert to ints.

**Comment by fscottfoti** [comment] 2017-03-10 22:33
Actually, I'm going to close this since the heading is misleading.  Will open another issue with a better name for the issue.

**Closed by fscottfoti** 2017-03-10 22:33 UTC
